import { createHash } from 'node:crypto';
import { typedError } from './errors.js';
export const REPLAY_LIMITS = Object.freeze({ fixtures: 1024, questions: 256, options: 256, levels: 256, stateBytes: 1_000_000, canonicalBytes: 4_000_000, aggregateBytes: 16_000_000, depth: 128, nodes: 100_000, keys: 10_000, arraySlots: 100_000 });
const cmp=(a:string,b:string)=>a<b?-1:a>b?1:0;
function own(value:unknown, depth=0, state={nodes:0,slots:0}):unknown { if(++state.nodes>REPLAY_LIMITS.nodes||depth>REPLAY_LIMITS.depth) throw typedError('INVALID_INPUT','canonical'); if(value===null||typeof value==='boolean'||typeof value==='string') return value; if(typeof value==='number' && Number.isFinite(value) && !Object.is(value,-0)) return value; if(typeof value!=='object') throw typedError('INVALID_INPUT','canonical'); const o=value as object; if(Object.getPrototypeOf(o)!==Object.prototype&&Object.getPrototypeOf(o)!==null&&Object.getPrototypeOf(o)!==Array.prototype) throw typedError('INVALID_INPUT','canonical'); if(Array.isArray(o)){ if(o.length>REPLAY_LIMITS.arraySlots||Reflect.ownKeys(o).length!==o.length+1) throw typedError('INVALID_INPUT','canonical'); state.slots+=o.length; return o.map(v=>own(v,depth+1,state)); } const keys=Object.keys(o).sort(cmp); if(keys.length>REPLAY_LIMITS.keys||Reflect.ownKeys(o).some(k=>typeof k==='symbol')) throw typedError('INVALID_INPUT','canonical'); const out=Object.create(null) as Record<string,unknown>; for(const k of keys){const d=Object.getOwnPropertyDescriptor(o,k); if(!d||!d.enumerable||!('value'in d)||d.get||d.set) throw typedError('INVALID_INPUT','canonical'); Object.defineProperty(out,k,{value:own(d.value,depth+1,state),enumerable:true,writable:true,configurable:true});} return out; }
export const canonical=(value:unknown):string=>{ const v=own(value); const text=JSON.stringify(v,(k,x)=>x,0); if(text===undefined||Buffer.byteLength(text,'utf8')>REPLAY_LIMITS.canonicalBytes) throw typedError('INVALID_INPUT','canonical'); return text; };
export const detached=<T>(value:T):T=>own(value) as T;
export const HASH_DOMAINS={state:'yfere/state/v1',questions:'yfere/questions/v1',response:'yfere/response/v1',fixture:'yfere/fixture/v1'} as const;
export function manifestBytes(domain:string,value:unknown){return canonical({canonicalization:'yfere-json-v1',domain,value});}
export function hashManifest(domain:string,value:unknown){const bytes=manifestBytes(domain,value); if(domain===HASH_DOMAINS.state && Buffer.byteLength(canonical(value),'utf8')>REPLAY_LIMITS.stateBytes) throw typedError('INVALID_INPUT','state'); return createHash('sha256').update(bytes).digest('hex');}
