import { z } from 'zod';
import { canonical, hashManifest, REPLAY_LIMITS } from './canonical.js';
export { REPLAY_LIMITS } from './canonical.js';
const id=z.string().min(1).max(256), digest=z.string().regex(/^[0-9a-f]{64}$/), finite=z.number().finite();
// Zod's record parser reconstructs into ordinary objects; assignment to
// __proto__ then changes the prototype instead of preserving the identifier.
// Validate descriptors and reconstruct with defineProperty at the trust edge.
const record=(schema:z.ZodTypeAny, max:number,min=0,keySchema:z.ZodTypeAny=id)=>z.unknown().superRefine((v,c)=>{
  if(v===null||typeof v!=='object'||Array.isArray(v)||Object.getPrototypeOf(v)!==Object.prototype&&Object.getPrototypeOf(v)!==null){c.addIssue({code:z.ZodIssueCode.custom,message:'record required'});return;}
  const keys=Object.keys(v as object); if(keys.length<min||keys.length>max)c.addIssue({code:z.ZodIssueCode.custom,message:'record size out of bounds'});
  for(const key of keys){const d=Object.getOwnPropertyDescriptor(v,key);if(!d||!d.enumerable||!('value'in d)){c.addIssue({code:z.ZodIssueCode.custom,message:'record descriptor'});continue;}if(!keySchema.safeParse(key).success)c.addIssue({code:z.ZodIssueCode.custom,message:'record key'});if(!schema.safeParse(d.value).success)c.addIssue({code:z.ZodIssueCode.custom,message:'record value'});}
}).transform((v)=>{const out=Object.create(null) as Record<string,unknown>;for(const key of Object.keys(v as object)){const d=Object.getOwnPropertyDescriptor(v,key)!;Object.defineProperty(out,key,{value:schema.parse(d.value),enumerable:true,writable:true,configurable:true});}return out;});
const question=z.discriminatedUnion('kind',[z.object({kind:z.literal('choice'),instructions:z.string().min(1).max(4096),criteria:z.string().max(4096).optional(),options:record(z.string().min(1).max(512),REPLAY_LIMITS.options,1,id)}).strict(),z.object({kind:z.literal('noul'),instructions:z.string().min(1).max(4096),criteria:z.string().max(4096).optional()}).strict(),z.object({kind:z.literal('score'),instructions:z.string().min(1).max(4096),criteria:z.string().max(4096).optional(),levels:z.array(id).min(1).max(REPLAY_LIMITS.levels)}).strict()]);
const distribution=record(finite,REPLAY_LIMITS.options,0,id);
const answer=z.discriminatedUnion('kind',[z.object({kind:z.literal('choice'),winner:id,distribution,confidence:finite.optional()}).strict(),z.object({kind:z.literal('noul'),value:finite}).strict(),z.object({kind:z.literal('score'),level:id,distribution,expected:finite,confidence:finite.optional()}).strict()]);
const bounded=z.custom((v)=>{try{canonical(v);return true}catch{return false}},{message:'invalid bounded JSON'});
export const decisionRequestRaw=z.object({decisionId:id,runId:id,stage:z.enum(['persona','model','skill']),round:z.union([z.literal(1),z.literal(2)]),inputClasses:z.array(z.enum(['settled_prompt','persona_definitions','model_catalog_metadata','skill_catalog_metadata'])).min(1).max(4),logicalCallId:id,state:bounded,questions:record(question,REPLAY_LIMITS.questions,1,id),catalogSnapshotId:id,policyVersion:id,deadlineMs:z.number().int().nonnegative().safe(),retryBudget:z.number().int().nonnegative().safe(),requestedModel:id,providerMode:z.enum(['recorded','typesafe-jev']),stateHash:digest,questionSetHash:digest,providerContractHash:digest,sdkVersion:digest,responseHash:digest,fixtureVersion:z.string().regex(/^yfere-recorded\/v[1-9][0-9]{0,7}$/).optional(),fixtureHash:digest.optional()}).strict();
const responseRaw=z.object({decisionId:id,logicalCallId:id,provider:id,requestedModel:id,returnedModel:id.optional(),answers:record(answer,REPLAY_LIMITS.questions,0,id),usage:z.object({inputTokens:z.number().int().nonnegative().safe().optional(),outputTokens:z.number().int().nonnegative().safe().optional()}).strict().optional(),requestId:id.optional(),providerTimingMs:z.number().int().nonnegative().safe().optional(),providerBilling:z.union([finite,z.literal('unknown')]).optional(),elapsedMs:z.number().int().nonnegative().safe(),attempts:z.number().int().positive().safe(),provenance:z.enum(['synthetic','documented_example','recorded_live']),providerContractHash:digest,sdkVersion:digest,responseHash:digest}).strict();
export const decisionRequestSchema=decisionRequestRaw, decisionResponseSchema=responseRaw, questionSchema=question, answerSchema=answer;
export type DecisionRequest=z.infer<typeof decisionRequestRaw>; export type DecisionResponse=z.infer<typeof responseRaw>; export type Question=z.infer<typeof question>; export type Answer=z.infer<typeof answer>; export interface RecordedFixture extends DecisionRequest { response:DecisionResponse; provenance:DecisionResponse['provenance']; } export interface DecisionService { readonly providerMode?: DecisionRequest['providerMode']; readonly requestedModel?: string; evaluate(request:DecisionRequest,signal?:AbortSignal):Promise<DecisionResponse>; }
export const stateHash=(v:unknown)=>hashManifest('yfere/state/v1',v); export const questionSetHash=(v:unknown)=>hashManifest('yfere/questions/v1',v);
