import { statSync, openSync, readSync, closeSync } from 'node:fs';
import { decisionRequestRaw, type DecisionRequest, type DecisionResponse, type DecisionService, type RecordedFixture, stateHash, questionSetHash, REPLAY_LIMITS } from './contracts.js';
import { canonical, detached, hashManifest } from './canonical.js';
import { DecisionServiceError, typedError } from './errors.js';
import { admitDecisionResponse } from './admit-response.js';
const without=(o:Record<string,unknown>,...keys:string[])=>{const n=Object.create(null);for(const k of Object.keys(o))if(!keys.includes(k))Object.defineProperty(n,k,{value:o[k],enumerable:true,writable:true,configurable:true});return n;};
const responsePayload=(r:DecisionResponse)=>without(r as any,'responseHash');
const fixturePayload=(f:RecordedFixture)=>without(f as any,'fixtureHash');
export const responseHash=(r:DecisionResponse)=>hashManifest('yfere/response/v1',responsePayload(r));
export const fixtureHash=(f:RecordedFixture)=>hashManifest('yfere/fixture/v1',fixturePayload(f));
function parseBytes(bytes:Uint8Array):unknown { const copy=new Uint8Array(bytes); let text:string; try{text=new TextDecoder('utf-8',{fatal:true}).decode(copy);}catch{throw typedError('INVALID_INPUT','decode');} try{return JSON.parse(text);}catch{throw typedError('INVALID_INPUT','parse');} }
function sourceBytes(source:string|Uint8Array):Uint8Array { if(typeof source==='string'){try{const size=statSync(source).size;if(size>32_000_000)throw typedError('INVALID_INPUT','raw');const fd=openSync(source,'r');const out=new Uint8Array(32_000_001);const n=readSync(fd,out,0,out.length,0);closeSync(fd);if(n>32_000_000)throw typedError('INVALID_INPUT','raw');return out.slice(0,n);}catch(e){if(e instanceof DecisionServiceError)throw e;throw typedError('INVALID_INPUT','source');}} if(!(source instanceof Uint8Array))throw typedError('INVALID_INPUT','source'); if(source.byteLength>32_000_000)throw typedError('INVALID_INPUT','raw'); return new Uint8Array(source); }
function checkResponse(req:DecisionRequest,value:unknown):DecisionResponse {
 return admitDecisionResponse(req, value);
}
function sameBase(a:DecisionRequest,b:DecisionRequest){
 const normalize=(request:DecisionRequest, reference:DecisionRequest)=>({ ...request, responseHash:request.responseHash==='0'.repeat(64)?reference.responseHash:request.responseHash, fixtureHash:request.fixtureHash==='0'.repeat(64)?reference.fixtureHash:request.fixtureHash });
 return canonical(normalize(a,b))===canonical(normalize(b,b));
}
export class RecordedDecisionService implements DecisionService {
 private readonly fixtures:ReadonlyMap<string,RecordedFixture>;
 constructor(source:string|Uint8Array){ const parsed=parseBytes(sourceBytes(source)); if(!Array.isArray(parsed)||parsed.length>REPLAY_LIMITS.fixtures)throw typedError('INVALID_INPUT','collection'); const map=new Map<string,RecordedFixture>();let aggregate=0;for(const raw of parsed){if(raw===null||typeof raw!=='object'||Array.isArray(raw))throw typedError('INVALID_INPUT','fixture');const bytes=Buffer.byteLength(canonical(raw),'utf8');if(bytes>REPLAY_LIMITS.canonicalBytes||aggregate>REPLAY_LIMITS.aggregateBytes-bytes)throw typedError('INVALID_INPUT','budget');aggregate+=bytes;const f=raw as any;if(!['synthetic','documented_example','recorded_live'].includes(f.provenance)||f.provenance!==f.response?.provenance)throw typedError('INVALID_INPUT','fixture');const reqParsed=decisionRequestRaw.safeParse(without(f,'response','provenance'));if(!reqParsed.success||f.fixtureVersion!=='yfere-recorded/v1')throw typedError('INVALID_INPUT','request');const req=reqParsed.data as DecisionRequest;const response=checkResponse(req,f.response);if((response.responseHash!==req.responseHash&&req.responseHash!=='0'.repeat(64))||response.providerContractHash!==req.providerContractHash||response.sdkVersion!==req.sdkVersion||responseHash(response)!==req.responseHash&&req.responseHash!=='0'.repeat(64)||stateHash(req.state)!==req.stateHash||questionSetHash(req.questions)!==req.questionSetHash||fixtureHash(f)!==req.fixtureHash)throw typedError('INVALID_INPUT','hash');const key=canonical([req.runId,req.stage,req.logicalCallId]);if(map.has(key))throw typedError('INVALID_INPUT','duplicate');map.set(key,Object.freeze(detached(f)));}this.fixtures=map; }
 async evaluate(input:DecisionRequest,signal?:AbortSignal):Promise<DecisionResponse>{if(signal?.aborted)throw typedError('CANCELLED','deadline');const p=decisionRequestRaw.safeParse(input);if(!p.success)throw typedError('INVALID_INPUT');const req=p.data as DecisionRequest;if(req.deadlineMs<=0)throw typedError('DEADLINE_EXCEEDED','deadline');if(stateHash(req.state)!==req.stateHash||questionSetHash(req.questions)!==req.questionSetHash)throw typedError('NON_REPLAYABLE','replay');const f=this.fixtures.get(canonical([req.runId,req.stage,req.logicalCallId]));if(!f||!sameBase(req,without(f as any,'response','provenance') as DecisionRequest))throw typedError('NON_REPLAYABLE','replay');if(f.response.elapsedMs>=req.deadlineMs)throw typedError('DEADLINE_EXCEEDED','deadline');if(f.response.attempts-1>req.retryBudget)throw typedError('BUDGET_EXCEEDED','replay');return detached(f.response); }
}
export type { DecisionRequest,DecisionResponse,RecordedFixture,DecisionService } from './contracts.js';
