import { describe, expect, it } from 'vitest';
import { selectRoster, type SelectorInput } from '../src/selection/index.js';
import { loadCatalogSnapshot } from '../src/domain/catalog.js';
const skill = { id:'required', version:'1.0.0', contentHash:'a'.repeat(64), trust:'reviewed', description:'required', positiveExamples:['x'], negativeExamples:[], requiredCapabilities:[], requiredTools:[], prerequisites:[], sideEffectClass:'none', conflicts:[], instructionTokenEstimate:1, artifactFormats:['text'] };
const model = { id:'model', version:'1.0.0', provider:'fixture', requestedModel:'model', transport:'offline-fixture', availability:'available', authorization:'authorized', modalities:['text'], features:[], tools:[], contextLimit:100, dataHandling:'synthetic-only', authorizationScope:'offline', cost:{input:'unknown',output:'unknown'}, operationalEvidenceIds:[] };
const persona = (id:string, overrides={}) => ({ id, version:'1.0.0', role:id, positiveExamples:['x'], negativeExamples:[], requiredCapabilities:[], outputContract:'text', requiredSkillIds:[], defaultSkillIds:[], eligibleSkillIds:[], workspacePolicy:'isolated', artifactOwnership:'persona', reviewIndependence:true, ...overrides });
const catalog = loadCatalogSnapshot([{format:'json',text:JSON.stringify({kind:'skills',version:'1.0.0',records:[skill]})},{format:'json',text:JSON.stringify({kind:'models',version:'1.0.0',records:[model]})},{format:'json',text:JSON.stringify({kind:'personas',version:'1.0.0',records:[persona('writer'),persona('coder')]})}]);
const base = (overrides:Partial<SelectorInput>={}):SelectorInput => { const answers:any=overrides.answers??{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}}; const decisionService:any={evaluate:async (r:any)=>({decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{[Object.keys(r.questions)[0]!]:r.stage==='persona'?answers.persona:undefined},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion,responseHash:r.responseHash})}; return {catalog,settledPrompt:'do work',policy:{taskId:'task',taskAttemptId:'attempt',requiredCapabilities:[],requiredTools:[],requiredFeatures:[],contextLimit:50,allowedCapabilities:[],allowedTools:[],allowedSideEffects:['none'],workspaceMode:'isolated',maxAgents:1,admissionPolicy:'allow-fewer',mandatoryPersonaIds:[],budget:{sharedUnits:10},artifactPolicy:'exclusive',reviewRequired:false},answers,decisionService,...overrides}; };
describe('phase 5 selector',()=>{
 it('reports pre-aborted selection as CANCELLED before invoking the service',async()=>{ const controller=new AbortController(); controller.abort(); let invoked=false; await expect(selectRoster(base({signal:controller.signal,decisionService:{evaluate:async()=>{invoked=true;throw new Error('must not invoke');}}}))).rejects.toMatchObject({code:'CANCELLED'}); expect(invoked).toBe(false); });
 it('binds settled prompt into decision state and identity',async()=>{ const requests:any[]=[]; const service={evaluate:async(r:any)=>{requests.push(r);return {decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion,responseHash:r.responseHash};}}; await selectRoster(base({decisionService:service,settledPrompt:'first'})); await selectRoster(base({decisionService:service,settledPrompt:'second'})); expect(requests[0].stateHash).not.toBe(requests[1].stateHash); expect(requests[0].decisionId).not.toBe(requests[1].decisionId); expect(requests[0].logicalCallId).not.toBe(requests[1].logicalCallId); });
 it('reserves mandatory personas within maxAgents',async()=>{ const c=loadCatalogSnapshot([{format:'json',text:JSON.stringify({kind:'skills',version:'1.0.0',records:[skill]})},{format:'json',text:JSON.stringify({kind:'models',version:'1.0.0',records:[model]})},{format:'json',text:JSON.stringify({kind:'personas',version:'1.0.0',records:[persona('a'),persona('b'),persona('c')]})}]); const result=await selectRoster(base({catalog:c,policy:{...base().policy,maxAgents:2,mandatoryPersonaIds:['c']},answers:{persona:{kind:'choice',winner:'a',distribution:{a:.8,b:.2,c:0,none:0}}}})); expect(result.roster.members).toHaveLength(2); expect(result.roster.members.map(x=>x.personaId)).toEqual(['a','c']); });
 it('invokes the provider-neutral decision service with a bounded correlated request',async()=>{ let request:any; const result=await selectRoster(base({decisionService:{evaluate:async(r:any)=>{request=r;return {decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion,responseHash:r.responseHash};}}})); expect(result.kind).toBe('accepted'); expect(request.stage).toBe('persona'); expect(request.questions).toBeTruthy(); expect(request.catalogSnapshotId).toBe(catalog.snapshotId); });
 it('selects hard-eligible personas and returns a detached frozen assignment',async()=>{ const result=await selectRoster(base()); expect(result.kind).toBe('accepted'); expect(result.roster.members[0]).toMatchObject({personaId:'writer',modelId:'model',skillIds:[]}); expect(Object.isFrozen(result.roster)).toBe(true); });
 it('rejects a persona winner that was not offered',async()=>{ await expect(selectRoster(base({answers:{persona:{kind:'choice',winner:'missing',distribution:{writer:0,coder:0,none:1}}}}))).rejects.toMatchObject({code:'INVALID_DECISION'}); });
});