import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { selectRoster, type SelectorInput } from '../src/selection/index.js';
import { loadCatalogSnapshot } from '../src/domain/catalog.js';
import { RecordedDecisionService, fixtureHash, responseHash } from '../src/decisions/index.js';
const skill = { id:'required', version:'1.0.0', contentHash:'a'.repeat(64), trust:'reviewed', description:'required', positiveExamples:['x'], negativeExamples:[], requiredCapabilities:[], requiredTools:[], prerequisites:[], sideEffectClass:'none', conflicts:[], instructionTokenEstimate:1, artifactFormats:['text'] };
const model = { id:'model', version:'1.0.0', provider:'fixture', requestedModel:'model', transport:'offline-fixture', availability:'available', authorization:'authorized', modalities:['text'], features:[], tools:[], contextLimit:100, dataHandling:'synthetic-only', authorizationScope:'offline', cost:{input:'unknown',output:'unknown'}, operationalEvidenceIds:[] };
const persona = (id:string, overrides={}) => ({ id, version:'1.0.0', role:id, positiveExamples:['x'], negativeExamples:[], requiredCapabilities:[], outputContract:'text', requiredSkillIds:[], defaultSkillIds:[], eligibleSkillIds:[], workspacePolicy:'isolated', artifactOwnership:'persona', reviewIndependence:true, ...overrides });
const catalog = loadCatalogSnapshot([{format:'json',text:JSON.stringify({kind:'skills',version:'1.0.0',records:[skill]})},{format:'json',text:JSON.stringify({kind:'models',version:'1.0.0',records:[model]})},{format:'json',text:JSON.stringify({kind:'personas',version:'1.0.0',records:[persona('writer'),persona('coder')]})}]);
const base = (overrides:Partial<SelectorInput>={}):SelectorInput => { const answers:any=overrides.answers??{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}}; const decisionService:any={evaluate:async (r:any)=>{const response:any={decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{[Object.keys(r.questions)[0]!]:r.stage==='persona'?answers.persona:undefined},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion}; response.responseHash=responseHash(response); return response;}}; return {catalog,settledPrompt:'do work',policy:{taskId:'task',taskAttemptId:'attempt',requiredCapabilities:[],requiredTools:[],requiredFeatures:[],contextLimit:50,allowedCapabilities:[],allowedTools:[],allowedSideEffects:['none'],workspaceMode:'isolated',maxAgents:1,admissionPolicy:'allow-fewer',mandatoryPersonaIds:[],budget:{sharedUnits:10},artifactPolicy:'exclusive',reviewRequired:false},answers,decisionService,...overrides}; };
describe('phase 5 selector',()=>{
 it('rejects unknown selector keys at the public trust boundary',async()=>{ await expect(selectRoster(base({...({unknown:'x'} as any)}))).rejects.toMatchObject({code:'CONFIG_ERROR'}); });
 it('reports pre-aborted selection as CANCELLED before invoking the service',async()=>{ const controller=new AbortController(); controller.abort(); let invoked=false; await expect(selectRoster(base({signal:controller.signal,decisionService:{evaluate:async()=>{invoked=true;throw new Error('must not invoke');}}}))).rejects.toMatchObject({code:'CANCELLED'}); expect(invoked).toBe(false); });
 it('binds settled prompt into decision state and identity',async()=>{ const requests:any[]=[]; const service={evaluate:async(r:any)=>{requests.push(r);const response:any={decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion}; response.responseHash=responseHash(response); return response;}}; await selectRoster(base({decisionService:service,settledPrompt:'first'})); await selectRoster(base({decisionService:service,settledPrompt:'second'})); expect(requests[0].stateHash).not.toBe(requests[1].stateHash); expect(requests[0].decisionId).not.toBe(requests[1].decisionId); expect(requests[0].logicalCallId).not.toBe(requests[1].logicalCallId); });
 it('reserves mandatory personas within maxAgents',async()=>{ const c=loadCatalogSnapshot([{format:'json',text:JSON.stringify({kind:'skills',version:'1.0.0',records:[skill]})},{format:'json',text:JSON.stringify({kind:'models',version:'1.0.0',records:[model]})},{format:'json',text:JSON.stringify({kind:'personas',version:'1.0.0',records:[persona('a'),persona('b'),persona('c')]})}]); const result=await selectRoster(base({catalog:c,policy:{...base().policy,maxAgents:2,mandatoryPersonaIds:['c']},answers:{persona:{kind:'choice',winner:'a',distribution:{a:.8,b:.2,c:0,none:0}}}})); expect(result.roster.members).toHaveLength(2); expect(result.roster.members.map(x=>x.personaId)).toEqual(['a','c']); });
 it('invokes the provider-neutral decision service with a bounded correlated request',async()=>{ let request:any; const result=await selectRoster(base({decisionService:{evaluate:async(r:any)=>{request=r;const response:any={decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion}; response.responseHash=responseHash(response); return response;}}})); expect(result.kind).toBe('accepted'); expect(request.stage).toBe('persona'); expect(request.questions).toBeTruthy(); expect(request.catalogSnapshotId).toBe(catalog.snapshotId); });
 it('selects hard-eligible personas and returns a detached frozen assignment',async()=>{ const result=await selectRoster(base()); expect(result.kind).toBe('accepted'); expect(result.roster.members[0]).toMatchObject({personaId:'writer',modelId:'model',skillIds:[]}); expect(Object.isFrozen(result.roster)).toBe(true); });
 it('rejects a persona winner that was not offered',async()=>{ await expect(selectRoster(base({answers:{persona:{kind:'choice',winner:'missing',distribution:{writer:0,coder:0,none:1}}}}))).rejects.toMatchObject({code:'INVALID_DECISION'}); });
 it('rejects a response carrying the pending hash sentinel',async()=>{ await expect(selectRoster(base({decisionService:{evaluate:async(r:any)=>({decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion,responseHash:'0'.repeat(64)})}}))).rejects.toMatchObject({code:'INVALID_DECISION'}); });
 it('accepts a valid generation one replan and binds its parent lineage',async()=>{ const parentDecision='a'.repeat(64); const result=await selectRoster(base({generation:1,replan:{generation:1,parentRosterId:'parent-roster',parentDecisionLineage:[parentDecision],priorFailure:'replanEligible'}})); expect(result.kind).toBe('accepted'); expect(result.roster.generation).toBe(1); expect(result.roster.parentRosterId).toBe('parent-roster'); expect(result.roster.parentDecisionLineage).toContain(parentDecision); });
 it('replays the checked-in selector Stage 1 fixture end to end',async()=>{const fixture=readFileSync(new URL('./fixtures/selector-stage1.json',import.meta.url));const result=await selectRoster(base({runId:'fixture-run',decisionService:new RecordedDecisionService(fixture)}));expect(result.kind).toBe('accepted');expect(result.roster.members[0]?.personaId).toBe('writer');});
 it('replays checked-in Stage 1 plus selected Stage 2a/2b fixtures',async()=>{
  const model2={...model,id:'model2',requestedModel:'model2'};
  const stage2Persona=persona('writer',{eligibleSkillIds:['optional']});
  const optional={...skill,id:'optional',contentHash:'b'.repeat(64),description:'optional'};
  const c=loadCatalogSnapshot([{format:'json',text:JSON.stringify({kind:'skills',version:'1.0.0',records:[optional]})},{format:'json',text:JSON.stringify({kind:'models',version:'1.0.0',records:[model,model2]})},{format:'json',text:JSON.stringify({kind:'personas',version:'1.0.0',records:[stage2Persona]})}]);
  const result=await selectRoster(base({catalog:c,runId:'fixture-stage2',decisionService:new RecordedDecisionService(readFileSync(new URL('./fixtures/selector-stage2.json',import.meta.url)))}));
  expect(result.kind).toBe('accepted'); expect(result.trace.map(t=>t.stage)).toEqual(['persona','model','skill']);
 });
 it('cancels after an awaited decision stage',async()=>{const controller=new AbortController();let release!:()=>void;const service={evaluate:async(r:any)=>{await new Promise<void>(resolve=>{release=resolve});controller.abort();const response:any={decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion};response.responseHash=responseHash(response);return response;}};const pending=selectRoster(base({signal:controller.signal,decisionService:service}));release();await expect(pending).rejects.toMatchObject({code:'CANCELLED'});});
 it('rejects forged, duplicated, reused, exhausted, and sensitive replans',async()=>{
  const parent='a'.repeat(64);
  const cases=[
   {replan:{generation:1,parentRosterId:'../forged',parentDecisionLineage:[parent],priorFailure:'replanEligible'},code:'REPLAN_EXHAUSTED'},
   {replan:{generation:1,parentRosterId:'parent',parentDecisionLineage:[parent,parent],priorFailure:'replanEligible'},code:'REPLAN_EXHAUSTED'},
   {generation:2,replan:{generation:1,parentRosterId:'parent',parentDecisionLineage:[parent],priorFailure:'replanEligible'},code:'REPLAN_EXHAUSTED'},
   {generation:1,code:'REPLAN_EXHAUSTED'},
   {replan:{generation:1,parentRosterId:'parent',parentDecisionLineage:[parent],priorFailure:'none'},code:'REPLAN_EXHAUSTED'},
   {replan:{generation:1,parentRosterId:'parent',parentDecisionLineage:[parent],priorFailure:'replanEligible',token:'secret'},code:'REPLAN_EXHAUSTED'},
  ];
  for(const item of cases) { const {code: _code,...input}=item; await expect(selectRoster(base(input as any))).rejects.toMatchObject({code:'REPLAN_EXHAUSTED'}); }
 });
 it('abstains on none and rejects tied persona distributions',async()=>{
  await expect(selectRoster(base({answers:{persona:{kind:'choice',winner:'none',distribution:{writer:0,coder:0,none:1}}}}))).resolves.toMatchObject({kind:'abstained',code:'NO_MATCH'});
  await expect(selectRoster(base({answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:.5,coder:.5,none:0}}}}))).rejects.toMatchObject({code:'INVALID_DECISION'});
 });
 it('preserves pinned model and skill bypass order without invoking the service',async()=>{
  const pinned=persona('writer',{modelOverride:'model',skillsOverride:[]}); let calls=0;
  const c=loadCatalogSnapshot([{format:'json',text:JSON.stringify({kind:'skills',version:'1.0.0',records:[skill]})},{format:'json',text:JSON.stringify({kind:'models',version:'1.0.0',records:[model]})},{format:'json',text:JSON.stringify({kind:'personas',version:'1.0.0',records:[pinned]})}]);
  const result=await selectRoster(base({catalog:c,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,none:0}}},decisionService:{evaluate:async(r:any)=>{calls++;const response:any={decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion};response.responseHash=responseHash(response);return response;}}}));
  expect(calls).toBe(1); expect(result.trace.map(t=>[t.stage,t.bypassed])).toEqual([['persona',false],['model',true],['skill',true]]);
 });
 it('rejects aggregate policy failure instead of returning a partial roster',async()=>{
  await expect(selectRoster(base({policy:{...base().policy,maxAgents:3,admissionPolicy:'exact'}}))).rejects.toMatchObject({code:'INSUFFICIENT_ELIGIBLE_PERSONAS'});
 });
 it('rejects response hash and correlation mutations after content is otherwise valid',async()=>{
  for(const mutate of [
   (r:any)=>({...r,responseHash:'f'.repeat(64)}),
   (r:any)=>({...r,logicalCallId:'mutated'}),
  ]) await expect(selectRoster(base({decisionService:{evaluate:async(r:any)=>{const response:any={decisionId:r.decisionId,logicalCallId:r.logicalCallId,provider:'fixture',requestedModel:r.requestedModel,answers:{persona:{kind:'choice',winner:'writer',distribution:{writer:1,coder:0,none:0}}},elapsedMs:0,attempts:1,provenance:'synthetic',providerContractHash:r.providerContractHash,sdkVersion:r.sdkVersion};response.responseHash=responseHash(response);return mutate(response);}}}))).rejects.toMatchObject({code:'INVALID_DECISION'});
 });
 it('returns deeply detached output that cannot mutate subsequent decisions',async()=>{const first=await selectRoster(base());expect(Object.isFrozen(first.roster.members[0])).toBe(true);expect(()=>{(first.roster.members as any)[0].personaId='tampered';}).toThrow();const second=await selectRoster(base());expect(second.roster.members[0]?.personaId).toBe('writer');});
});