import { hashManifest } from '../decisions/canonical.js';
import { stateHash } from '../decisions/contracts.js';
import { DecisionServiceError } from '../decisions/errors.js';
import { admitDecisionResponse } from '../decisions/admit-response.js';
import { detached } from '../policy/contracts.js';
import { reconcileTeam } from '../policy/index.js';
import type { PersonaDefinition, ModelEndpoint, SkillDefinition } from '../domain/catalog.js';
import { SelectorError, type SelectorInput, type SelectionResult, type AssignmentMember, type AssignmentRoster, type DecisionTrace, type ChoiceAnswer, type PersonaOverride } from './contracts.js';
import { normalizeSelectorInput } from './input.js';
import { buildDecisionRequest } from './decision-call.js';
export * from './contracts.js';
const cmp=(a:string,b:string)=>a<b?-1:a>b?1:0;
const sorted=(xs:readonly string[])=>[...xs].sort(cmp);
function fail(code:any,message='invalid selector input'):never { throw new SelectorError(code,message); }
function safe(value:unknown):boolean { return typeof value==='string' && value.length>0 && value.length<=128 && /^[a-zA-Z0-9][a-zA-Z0-9._:-]*$/.test(value) && !value.includes('..') && !value.includes('://'); }
function choice(value:unknown, offered:readonly string[], stage:string):ChoiceAnswer {
 if(!value||typeof value!=='object'||(value as any).kind!=='choice') fail('INVALID_DECISION');
 const v=value as any, keys=Object.keys(v); if(keys.some(k=>!['kind','winner','distribution'].includes(k))) fail('INVALID_DECISION');
 if(typeof v.winner!=='string'||!offered.includes(v.winner)||!v.distribution||typeof v.distribution!=='object'||Array.isArray(v.distribution)) fail('INVALID_DECISION');
 const d=v.distribution as Record<string,unknown>; if(Object.keys(d).length!==offered.length||offered.some(id=>!Object.prototype.hasOwnProperty.call(d,id))) fail('INVALID_DECISION');
 let total=0; for(const id of offered){const n=d[id];if(typeof n!=='number'||!Number.isFinite(n)||n<0)fail('INVALID_DECISION');total+=n;}
 if(Math.abs(total-1)>1e-9) fail('INVALID_DECISION');
 const max=Math.max(...offered.map(id=>d[id] as number)); if(offered.filter(id=>d[id]===max).length!==1||d[v.winner]!==max) fail('INVALID_DECISION');
 return {kind:'choice',winner:v.winner,distribution:Object.fromEntries(offered.map(id=>[id,d[id] as number]))};
}
function hardEligible(p:PersonaDefinition,catalog:SelectorInput['catalog'],policy:SelectorInput['policy']):boolean { if(!p.requiredCapabilities.every(x=>policy.allowedCapabilities.includes(x))||!p.requiredSkillIds.every(x=>p.eligibleSkillIds.includes(x)))return false;const skills=catalog.skills.filter(s=>p.requiredSkillIds.includes(s.id));return skills.length===p.requiredSkillIds.length&&skills.every(s=>s.trust==='reviewed')&&catalog.models.some(m=>compatible(p,m,skills,policy)); }
function compatible(p:PersonaDefinition,m:ModelEndpoint,skills:readonly SkillDefinition[],policy:SelectorInput['policy']):boolean { return m.availability==='available'&&m.authorization==='authorized'&&m.contextLimit>=policy.contextLimit&&policy.requiredFeatures.every(x=>m.features.includes(x))&&policy.requiredTools.every(x=>m.tools.includes(x))&&p.requiredCapabilities.every(x=>policy.allowedCapabilities.includes(x))&&skills.every(s=>s.trust==='reviewed'&&s.requiredCapabilities.every(x=>policy.allowedCapabilities.includes(x))&&s.requiredTools.every(x=>policy.allowedTools.includes(x)&&m.tools.includes(x))&&policy.allowedSideEffects.includes(s.sideEffectClass)); }
function optionsFor(p:PersonaDefinition,catalog:SelectorInput['catalog'],policy:SelectorInput['policy'],override?:PersonaOverride){const exact=override?.skills&&override.skills!=='auto'?new Set(override.skills):undefined;const ids=exact?sorted([...exact]):sorted([...new Set([...p.requiredSkillIds,...p.defaultSkillIds])]);const skills=catalog.skills.filter(s=>ids.includes(s.id));if(skills.length!==ids.length||!ids.every(id=>p.eligibleSkillIds.includes(id))||!p.requiredSkillIds.every(id=>ids.includes(id)))fail('INCOMPATIBLE');const models=catalog.models.filter(m=>(!override?.model||m.id===override.model)&&(!p.modelOverride||m.id===p.modelOverride)&&compatible(p,m,skills,policy)).sort((a,b)=>cmp(a.id,b.id));if(!models.length)fail('INCOMPATIBLE');return {models,skills};}
function memberId(run:string,attempt:string,generation:number,ordinal:number,p:string,m:string,skills:readonly string[]){return hashManifest('yfere/assignment/v2',{run,attempt,generation,ordinal,p,m,s:sorted(skills)}).slice(0,32);}
function rosterId(members:readonly AssignmentMember[],generation:number,parent:string|undefined,lineage:readonly string[]){return hashManifest('yfere/roster/v2',{generation,...(parent?{parent}:{}),lineage,members});}

async function decide(input:SelectorInput,stage:'persona'|'model'|'skill',offered:readonly string[],key:string,round:1|2,legacy:unknown):Promise<{answer:ChoiceAnswer;trace:DecisionTrace}>{ const req=buildDecisionRequest(input,stage,offered,key,round);let raw:any;if(input.signal?.aborted)fail('CANCELLED');if(input.decisionService){try{raw=await input.decisionService.evaluate(req,input.signal);}catch(e:unknown){if(e instanceof DecisionServiceError){const code=e.code==='CANCELLED'?'CANCELLED':e.code==='DEADLINE_EXCEEDED'?'DEADLINE_EXCEEDED':e.code==='BUDGET_EXCEEDED'?'BUDGET_EXCEEDED':e.code==='NON_REPLAYABLE'?'NON_REPLAYABLE':'INVALID_DECISION';fail(code);}fail('DECISION_SERVICE_ERROR');}if(input.signal?.aborted)fail('CANCELLED');try{const admitted=admitDecisionResponse(req,raw);const answers=admitted.answers;if(Object.keys(answers).length!==1||!Object.prototype.hasOwnProperty.call(answers,key))fail('INVALID_DECISION');raw=answers[key];}catch(e:unknown){if(e instanceof DecisionServiceError)fail('INVALID_DECISION');throw e;}}else raw=legacy;if(raw===undefined)fail('INVALID_DECISION');const answer=choice(raw,offered,stage);return {answer,trace:{stage,questionIds:[key],offeredIds:[...offered],winner:answer.winner,distribution:answer.distribution,bypassed:false,decisionId:req.decisionId,logicalCallId:req.logicalCallId,requestHash:stateHash(req),responseHash:stateHash(answer)}}; }
export async function selectRoster(input:SelectorInput):Promise<SelectionResult>{
 if(input.signal?.aborted)fail('CANCELLED');
 input=normalizeSelectorInput(input);
 if(input.signal?.aborted)fail('CANCELLED');if(!input.decisionService)fail('CONFIG_ERROR');if(input.policy.maxAgents<1||input.policy.maxAgents>4||input.policy.mandatoryPersonaIds.length>input.policy.maxAgents)fail('CONFIG_ERROR');
 for(const id of [...input.policy.mandatoryPersonaIds,...Object.keys(input.overrides??{})])if(!safe(id))fail('CONFIG_ERROR');
 const generation=input.replan?.generation??input.generation??0;if(!Number.isSafeInteger(generation)||generation<0||generation>1)fail('REPLAN_EXHAUSTED');
 const parentId=input.replan?.parentRosterId;const parentLineage=input.replan?.parentDecisionLineage??[];
 const catalog=input.catalog, personas=[...catalog.personas].sort((a,b)=>cmp(a.id,b.id)), eligible=personas.filter(p=>hardEligible(p,catalog,input.policy));for(const id of input.policy.mandatoryPersonaIds)if(!eligible.some(p=>p.id===id))fail('NO_MATCH');
  const offers=sorted([...eligible.map(p=>p.id),'none']), traces:DecisionTrace[]=[];const pa=await decide(input,'persona',offers,'persona',1,input.answers?.persona);traces.push(pa.trace);if(pa.answer.winner==='none'){const roster:AssignmentRoster={rosterId:rosterId([],generation,parentId,parentLineage.concat(traces.flatMap(t=>t.decisionId ? [t.decisionId] : []))),generation,...(parentId?{parentRosterId:parentId}:{}),parentDecisionLineage:[...(parentLineage.concat(traces.flatMap(t=>t.decisionId ? [t.decisionId] : [])))],members:[]};return detached({kind:'abstained',code:'NO_MATCH',roster,trace:traces});}
 const ranked=offers.filter(x=>x!=='none').sort((a,b)=>((pa.answer.distribution[b]??0)-(pa.answer.distribution[a]??0))||cmp(a,b));const mandatory=sorted(input.policy.mandatoryPersonaIds);let selected=[...mandatory,...ranked.filter(id=>!mandatory.includes(id)).slice(0,Math.max(0,input.policy.maxAgents-mandatory.length))];selected=sorted(selected);if(selected.length<input.policy.maxAgents&&input.policy.admissionPolicy==='exact')fail('INSUFFICIENT_ELIGIBLE_PERSONAS');
 const candidates:any[]=[];const members:AssignmentMember[]=[];for(const pid of selected){const p=personas.find(x=>x.id===pid)!;const supplied=input.overrides?.[pid];const override=supplied??(p.modelOverride||p.skillsOverride?{...(p.modelOverride?{model:p.modelOverride}:{}),...(p.skillsOverride?{skills:p.skillsOverride}:{} )}:undefined);const opts=optionsFor(p,catalog,input.policy,override);let model=opts.models[0]!;if(override?.model||p.modelOverride){traces.push({stage:'model',questionIds:[`model:${pid}`],offeredIds:[model.id],winner:model.id,distribution:{[model.id]:1},bypassed:true});}if(opts.models.length>1&&!override?.model&&!p.modelOverride){const ma=await decide(input,'model',opts.models.map(x=>x.id),`model:${pid}`,2,input.answers?.model?.[pid]);traces.push(ma.trace);model=opts.models.find(x=>x.id===ma.answer.winner)!;}let skills=opts.skills;const exact=override?.skills&&override.skills!=='auto';if(exact){traces.push({stage:'skill',questionIds:[`skill:${pid}`],offeredIds:skills.map(s=>s.id),winner:skills[0]?.id ?? '',distribution:Object.fromEntries(skills.map(s=>[s.id,1/skills.length])),bypassed:true});}if(!exact){const optional=catalog.skills.filter(s=>p.eligibleSkillIds.includes(s.id)&&!skills.some(x=>x.id===s.id)&&compatible(p,model,[...skills,s],input.policy)).map(s=>s.id).sort(cmp);if(optional.length){const sa=await decide(input,'skill',[...optional,'none'],`skill:${pid}`,2,input.answers?.skill?.[pid]);traces.push(sa.trace);if(sa.answer.winner!=='none')skills=[...skills,catalog.skills.find(s=>s.id===sa.answer.winner)!];}}if(!compatible(p,model,skills,input.policy))fail('INCOMPATIBLE');const capabilities=sorted([...new Set([...p.requiredCapabilities,...skills.flatMap(s=>s.requiredCapabilities),...input.policy.requiredCapabilities])]);const tools=sorted([...new Set([...input.policy.requiredTools,...skills.flatMap(s=>s.requiredTools)])]);candidates.push({candidateId:pid,personaId:pid,modelId:model.id,skillIds:skills.map(s=>s.id),capabilities,tools,contextUse:skills.reduce((n,s)=>n+s.instructionTokenEstimate,0),sideEffect:skills.some(s=>s.sideEffectClass==='external')?'external':skills.some(s=>s.sideEffectClass==='workspace')?'workspace':'none',workspaceMode:input.policy.workspaceMode,reservation:'unknown',artifacts:[],reviews:[]});members.push({memberId:memberId(input.runId??input.policy.taskId,input.policy.taskAttemptId,generation,members.length,pid,model.id,skills.map(s=>s.id)),ordinal:members.length,personaId:pid,modelId:model.id,skillIds:skills.map(s=>s.id)});}
 const checked=reconcileTeam({catalog,policy:input.policy,candidates});if(checked.kind!=='accepted')fail('INCOMPATIBLE');members.sort((a,b)=>cmp(a.personaId,b.personaId));const roster:AssignmentRoster={rosterId:rosterId(members,generation,parentId,parentLineage.concat(traces.flatMap(t=>t.decisionId ? [t.decisionId] : []))),generation,...(parentId?{parentRosterId:parentId}:{}),parentDecisionLineage:[...(parentLineage.concat(traces.flatMap(t=>t.decisionId ? [t.decisionId] : [])))],members};return detached({kind:'accepted',roster,trace:traces});
}
export const select=selectRoster;
export type { SelectorInput as SelectionInput } from './contracts.js';
